SELECT UPPER(ENAME) AS NAME, LENGTH(ENAME) AS "LENGTH OF NAME"
FROM EMP

SELECT ENAME, CONCAT(CONCAT(SUBSTR(JOB, 0,3), '-'),SUBSTR(JOB, -3)) AS "JOBS"
FROM EMP


SELECT ENAME, CONCAT('HIRED ON ', TO_CHAR(HIREDATE, 'DD-Month-YYYY')) AS "DATE OF HIRE"   --TO_CHAR WORK ON DATES, NUMBERS, AND STRINGS. Converts each to datatype to its given format. TO_DATE converts a character to date
FROM EMP


--rounding to the nearest 1000 (-3) [800 -> 1000, 1250 -> 1000] and truncating to the nearest 100 (-2) [950 -> 900, 2975 -> 2900]
SELECT SAL, ROUND(SAL, 3), ROUND(SAL, -3), TRUNC(SAL, -2)  
FROM EMP

SELECT REPLACE(ENAME, 'A', '@') AS "EN@MAE" --REPLACE() REPLACES CHARACTERS
FROM EMP

SELECT DEPTNO, AVG(SAL) AS "AVERAGE SALARY", MAX(SAL) AS "MAXIMUM SLALRY", MIN(SAL) AS "MINIMUM SALARY" 
FROM EMP
GROUP BY DEPTNO

SELECT DEPTNO, AVG(SAL) AS "AVAERAGE SALARY"
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) > 2000 

--TOTAL NUMBER OF EMPLOYEES HIRED AT THE BEGINNING OF EACH YEAR 
SELECT COUNT(*) AS "NUMBER OF EMPLOYEES HIRED", TRUNC(HIREDATE, 'YEAR') AS "DATE OF HIRE"
FROM EMP 
GROUP BY TRUNC(HIREDATE, 'YEAR')
ORDER BY 2

--BEGINNING OF THE YEAR
SELECT TRUNC(HIREDATE,'YEAR'), HIREDATE FROM EMP
GROUP BY HIREDATE



-- Employees whose salary is greater than average salary of all employees
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP)



--employees who earn the maximum salary in their department
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO
--with subquery. outputs 1 more record compared to the query above
SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)

--
SELECT * --D.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO != D.DEPTNO 
AND (SELECT DEPTNO FROM DEPT  WHERE)


SELECT * FROM DEPT D LEFT JOIN EMP E
ON D.DEPTNO = E.DEPTNO
WHERE EMPNO IS NULL
--




-- employees whose commision is haigher than average 
SELECT ENAME, COMM
FROM EMP
WHERE COMM > (SELECT AVG(COMM) FROM EMP );


--departments that have no employees **
SELECT *
FROM (SELECT * FROM EMP E FULL JOIN DEPT D ON E.DEPTNO = D.DEPTNO ) DEPTEMP
WHERE EMPNO IS NULL

-- list employees with their department name and location
SELECT E.ENAME, D.DNAME, D.LOC
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

--list all departments, even those without employees 
SELECT D.DEPTNO, D.DNAME, E.ENAME
FROM EMP E
FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO ;

-- employees working in SMITH'S department
SELECT * 
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = (SELECT DEPT.DNAME FROM DEPT INNER JOIN EMP ON EMP.DEPTNO = DEPT.DEPTNO  WHERE EMP.ENAME = 'SMITH'); --subquery result is SMITH'S department name


-- list the total salary of each department 
SELECT D.DNAME, NVL(SUM(SAL), 0) AS TOTAL_SALARY --replacing null values with 0
FROM EMP E
FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
GROUP BY D.DNAME
ORDER BY 2 DESC

-- List employee names with their commision. If null, put 0
SELECT ENAME, NVL(COMM,0) AS COMMISION
FROM EMP 

--COMBINE COMMISION AND SALRY
SELECT ENAME, NVL(COMM,0), SAL + NVL(COMM,0) AS COMBINED_COMMISION_AND_SALARY, SAL
FROM EMP

--CONCATENATION
SELECT CONCAT(CONCAT(CONCAT(LOWER(JOB), ' if '),'JOB = '),JOB)
FROM EMP
--2
SELECT LOWER(JOB)|| ' if '||' JOB = '|| JOB
FROM EMP

-- LIST the departments and their average salary as well as the number of employees working in each of them
SELECT D.DNAME, COUNT(EMPNO) as NUM_OF_EMPLOYEES, ROUND(NVL(AVG(SAL),0),2) AS AVAERAGE_SALARY
FROM EMP E
FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
GROUP BY D.DNAME
ORDER BY 3 DESC

--LIST records in which they have same job with employee 7902
SELECT *
FROM EMP
WHERE JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7902 ) --subquery returns the job title of the employee with employee number 7902

--List the number of people that work in each department
SELECT COUNT(*), DNAME
FROM EMP E
FULL JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
GROUP BY D.DNAME
